## Simulación de datos de usuario.

In [2]:
import random as rand
import pandas as pd
import numpy as np
from faker import Faker

In [12]:
fake = Faker('es_ES')

usuarios = []
mentores = []

# Generar datos para 1000 usuarios
for _ in range(1000):
    usuario = {
        'nombre': fake.name(),
        'direccion': fake.address(),
        'correo': fake.email(),
        'telefono': fake.phone_number(),
        'profesion': fake.job(),
        'genero': rand.choices(['masculino', 'femenino', 'intergenero', 'nc'], weights=[0.45, 0.45, 0.05, 0.05])[0],
        'edad': rand.randint(18, 65),
        'password': fake.password(),
        'encuesta': rand.choice(['si', 'no'])
    }
    usuarios.append(usuario)

# Generar datos para 100 mentores
for _ in range(100):
    mentor = {
        'nombre': fake.name(),
        'direccion': fake.address(),
        'correo': fake.email(),
        'telefono': fake.phone_number(),
        'profesion': 'psicológo',
        'genero': rand.choices(['masculino', 'femenino', 'intergenero', 'nc'], weights=[0.45, 0.45, 0.05, 0.05])[0],
        'edad': rand.randint(18, 65),
        'password': fake.password(),
        'eventos': rand.choice(['si', 'no'])
    }
    mentores.append(mentor)

# Convertir las listas en DataFrames
df_usuarios = pd.DataFrame(usuarios)
df_mentores = pd.DataFrame(mentores)

In [11]:
df_usuarios.head()
df_mentores.head()

,nombre,direccion,correo,telefono,profesion,genero,edad,password,eventos
0,Jerónimo Montero Sales,"Camino de Otilia Fábregas 744\nAlicante, 21931",estradabruno@example.org,+34879506396,psicológo,femenino,73,6YQ(X$$h^o,si
1,Trinidad Merino Pintor,"Vial Araceli Tejera 18 Puerta 7 \nLleida, 03340",valeriahoz@example.org,+34 902 129 327,psicológo,femenino,91,^0IZd#6S@T,no
2,Luis Martinez Alfonso,"Vial de Isa Torrens 429 Puerta 2 \nSalamanca, ...",cepedaluciana@example.com,+34 611 26 94 98,psicológo,masculino,75,U7CE%3Am*4,no
3,Cruz Rojas Segovia,"Pasaje de Ruperto Álamo 21\nCuenca, 45726",emperatriz53@example.com,+34902 877 725,psicológo,masculino,51,M+4U%pR$fn,no
4,Laura de Ocaña,"C. Gabino Pizarro 51 Apt. 44 \nLleida, 13213",blanca63@example.org,+34 872 113 600,psicológo,masculino,38,2(oDUhmM)z,si

In [21]:
encuestas = []
for _ in range(300):
    encuesta = {
        'tristeza': rand.randint(0, 3),
        'pesimismo': rand.randint(0, 3),
        'fracaso': rand.randint(0, 3),
        'perdida_placer': rand.randint(0, 3),
        'culpa': rand.randint(0, 3),
        'castigo': rand.randint(0, 3),
        'disconformidad': rand.randint(0, 3),
        'autocritica': rand.randint(0, 3),
        'suicidio': rand.randint(0, 3),
        'llanto': rand.randint(0, 3),
        'agitacion': rand.randint(0, 3),
        'interes': rand.randint(0, 3),
        'indeciso': rand.randint(0, 3),
        'desvalorizacion': rand.randint(0, 3),
        'energia': rand.randint(0, 3),
        'irritabilidad': rand.randint(0, 3),
        'concentracion': rand.randint(0, 3),
        'cansancio': rand.randint(0, 3),
        'sexo': rand.randint(0, 3)
    }
    encuestas.append(encuesta)

df_encuestas = pd.DataFrame(encuestas)

In [23]:
df_encuestas.head()

,tristeza,pesimismo,fracaso,perdida_placer,culpa,castigo,disconformidad,autocritica,suicidio,llanto,agitacion,interes,indeciso,desvalorizacion,energia,irritabilidad,concentracion,cansancio,sexo
0,1,2,0,3,2,1,0,0,0,1,3,1,3,2,1,2,2,2,1
1,3,3,3,3,1,2,3,3,3,0,1,3,1,2,1,1,2,0,3
2,1,3,0,2,1,2,0,2,0,0,3,0,0,0,3,1,2,1,2
3,3,1,3,2,1,1,2,0,3,1,1,0,2,2,0,3,0,1,3
4,1,3,0,3,2,0,1,1,2,2,3,2,1,3,3,3,1,3,1